"""make mission created_by nullable

Revision ID: 16d9fe68590c
Revises: 55ce72826a8e
Create Date: 2026-09-04 16:02:16.959154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d9fe68590c'
down_revision: Union[str, Sequence[str], None] = '55ce72826a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
