"""add planned_path to tasks

Revision ID: 5862802655d6
Revises: 16d9fe68590c
Create Date: 2026-09-04 16:15:39.782345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5862802655d6'
down_revision: Union[str, Sequence[str], None] = '16d9fe68590c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('planned_path', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'planned_path')
    # ### end Alembic commands ###
